{% set name = "dirty-equals" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 798db3b9481b9a5024c0e520946507676ed2f0c65317d3e95bdce1a01657cf60

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - hatchling
    - python >=3.8
  run:
    - python >=3.8
    - pytz >=2021.3

test:
  imports:
    - dirty_equals
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://dirty-equals.helpmanual.io
  summary: Doing dirty (but extremely useful) things with equals.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/samuelcolvin/dirty-equals

extra:
  recipe-maintainers:
    - nicoddemus
