{% set name = "dirty-equals" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a580513f3285e93656a770a04e428f8bfc513848877bf278282dbfbb907fdbb4

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - hatchling
    - python >=3.7
  run:
    - python >=3.7
    - pytz >=2021.3
    - typing-extensions

test:
  imports:
    - dirty_equals
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://dirty-equals.helpmanual.io
  summary: Doing dirty (but extremely useful) things with equals.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/samuelcolvin/dirty-equals

extra:
  recipe-maintainers:
    - nicoddemus
