{% set name = "dirty-equals" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 17f515970b04ed7900b733c95fd8091f4f85e52f1fb5f268757f25c858eb1f7b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pytz >=2021.3

test:
  imports:
    - dirty_equals
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://dirty-equals.helpmanual.io
  summary: Doing dirty (but extremely useful) things with equals.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/samuelcolvin/dirty-equals

extra:
  recipe-maintainers:
    - nicoddemus
