{% set name = "dirty-equals" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f107137476d784b7f86757a3e1291fe11e8166d4720df9c02a3ee5dfa595e1fe

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - hatchling
    - python >=3.7
  run:
    - python >=3.7
    - pytz >=2021.3
    - typing-extensions

test:
  imports:
    - dirty_equals
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://dirty-equals.helpmanual.io
  summary: Doing dirty (but extremely useful) things with equals.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/samuelcolvin/dirty-equals

extra:
  recipe-maintainers:
    - nicoddemus
