{% set name = "dirty-equals" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dirty-equals-{{ version }}.tar.gz
  sha256: c05286ecfb19de44c4ceaa44ac68c77df1cbea9a69e65ad72cbdd4e0d3aa6477

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python
  run:
    - python
    - pytz >=2021.3,<2022.0
    - typing-extensions >=4.0.1,<5.0.0  # [py<38]

test:
  imports:
    - dirty_equals
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://dirty-equals.helpmanual.io
  summary: Doing dirty (but extremely useful) things with equals.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/samuelcolvin/dirty-equals

extra:
  recipe-maintainers:
    - nicoddemus
